### ISSUE TITLE
repository column in the github_search_issue table is always null

### ISSUE THREAD

**Issue by misraved** [turbot/steampipe-plugin-github#124]
**Describe the bug**
When we try to query the `repository` column in the `github_search_issue` table always return null

**Steampipe version (`steampipe -v`)**
Example: v0.11.1

**Plugin version (`steampipe plugin list`)**
Example: v0.10.1

**To reproduce**
1. Run the following query - 
```
 select
  title,
  id,
  state,
  created_at,
  closed_at,
  html_url,
  repository,
  repository_url
from
  github_search_issue
where
  query = 'org:turbot state:closed'
  and closed_at > (created_at + interval '30' day);
  ```
  We observe that the repository column is always null

**Expected behavior**
`repository` column should include the details of the repository

**Additional context**

**Comment by ParthaI** [comment]
Raised an issue on go SDK repo for github, [Issue Link](https://github.com/google/go-github/issues/2245)

**Comment by ParthaI** [comment]
This is expected behaviour of api.
 Please check out the official GitHub v3 API documentation:
https://docs.github.com/en/rest/reference/search#search-issues-and-pull-requests
and notice that in their example, no "repository" object is returned.
You can see the other fields that are returned, for example repository_url.

Note that there are many cases in this repo where Go structs have fields that are not always fully populated because they are being used in numerous different scenarios.
