### ISSUE TITLE
Add repository_full_name column in github_search_* tables

### ISSUE THREAD

**Issue by rajlearner17** [turbot/steampipe-plugin-github#129]
**Is your feature request related to a problem? Please describe.**

[Reference](https://github.com/turbot/steampipe-plugin-github/issues/122) 

**Describe the solution you'd like**

**Describe alternatives you've considered**

**Additional context**

**Comment by ParthaI** [comment]
- We can not have `repository_full_name` in `turbot_search_user` because the user can be collaborate in multiple repos, so we can have a slice of repository full names in per row.
- We are not getting any details of repository in `github_search_topic` table so we can not add the repository_full_name column here.
