### ISSUE TITLE
github_user.email is always null

### ISSUE THREAD

**Issue by chrisj-back2work** [turbot/steampipe-plugin-github#211]
**Describe the bug**
I expected the email column to be in the result set when querying `github_user`, but it's always null.

Verified my Github PAT has the permissions described on https://hub.steampipe.io/plugins/turbot/github, incl `user:email`.

**Steampipe version (`steampipe -v`)**
Example: v0.16.4

**Plugin version (`steampipe plugin list`)**
Example: v0.22.1

**To reproduce**
Run this query: `select * from github_user where login = 'A_REAL_LOGIN_FROM_YOUR_ORG';`

**Expected behavior**
Email address should be returned; not null.

**Additional context**
N/A

**Comment by cbruno10** [comment]
@chrisj-back2work For the user(s) that you're querying, and not seeing an email when you expect to, do they have public email addresses, e.g., you can see their email on their user page like https://github.com/cbruno10? For instance, if you run `select login, email from github_user where login = 'cbruno10'`, `email` will be `null` since I don't have a public email address. However, when I query a user with a public email, e.g., `select login, email from github_user where login = 'mtodd'`, I get a value in the `email` column.
