### ISSUE TITLE
Update documentation with instructions on using fine-grained access tokens

### ISSUE THREAD

**Issue by cbruno10** [turbot/steampipe-plugin-github#311]
**Is your feature request related to a problem? Please describe.**
If I am trying to use a [fine-grained access tokens](https://docs.github.com/en/authentication/keeping-your-account-and-data-secure/managing-your-personal-access-tokens#creating-a-fine-grained-personal-access-token), I don't know how to configure them for use with the plugin

**Describe the solution you'd like**
Update `docs/index.md` with instructions and scope information

**Describe alternatives you've considered**
Using classic PATs

**Additional context**
- Fine-grained access tokens can be owned by a user or organization, I believe tokens owned by organizations is required because only organization owned tokens can be assigned Organization and Repository permissions, while user owned tokens can be assigned Repository and Account permissions
- To create an organization owned token, the organization needs to opt-in to allow users to create them
- Some scopes only offer No access and Read and write permissions, so Read and write may be required sometimes
- Some tables return 0 rows instead of errors when using user owned tokens, e.g., `select * from github_my_team` returns 0 rows

Open questions:
- Can user owned tokens be used, or just organization owned tokens?
  - If user owned tokens can be used, which tables work?
- Do any tables need permissions that only have "No access" and "Read and write" permissions?
  - In general, I think we can recommend starting with suggesting "Read-only" permissions on all Repository/Organization permission scopes, since they're lower risk, but write permissions are higher risk.
- Are there any tables that will throw `Error: Resource not accessible by personal access token` even if all read permissions are granted?
  - It seems like `github_repository` and `github_my_repository` table queries always have that error, when selecting a single column that doesn't require a hydrate.
- Are there any tables that return unexpected or no results?
  - When using a user owned token, querying the `github_my_team` table returns 0 rows, but if using a classic token or organization owned token, it returns the correct results.

**Comment by graza-io** [comment]
## Quick Summary of Fine-Grained (Org Based) vs Classic PAT.

**Tested with org fine-grained token, all permissions set to `read-only` (or `read-write` when `read-only` not applicable)**

Where with classic certain fields we didn't have permissions to view returned `null` or `""` without error - now return errors with the fine-grained access token.
- This results in some `REST` endpoints (one example being hooks on org tables) now returning error instead of returning `null` if user doesn't have permissions.
- Also results in `GraphQL` returning errors (which causes the SDK to drop the data, even in event of data being returned with `null`/`""` values in fields).

`GraphQL` list of fields observed per table as having permission issues & causing errors:
- `github_repository` / `github_my_repository` / `github_team_repository`
  - `repository.tempCloneToken` (Note: this one also seemed to affect @cbruno10 even though he's admin)
  - `repository.branchProtectionRules`
- `github_branch_protection`
  - `repository.branchProtectionRules`
- `github_team` / `github_my_team`
  - `team.invitations.totalCount`

`REST` based issues
- `github_audit_log` (Note: this one appears to be due to being Enterprise only)
- `github_organization` / `github_my_organization` returns error `https://api.github.com/orgs/turbot/hooks?per_page=100: 403 Resource not accessible by personal access token` (with classic PAT returns `null`)
- `github_actions_repository_runner` returns error `https://api.github.com/repos/turbot/steampipe/actions/runners?per_page=10: 403 Resource not accessible by personal access token` (with classic PAT returns error `https://api.github.com/repos/turbot/steampipe/actions/runners?per_page=10: 403 Must have admin rights to Repository.`)

**Comment by graza-io** [comment]
Answering `Open Questions`

> Can user owned tokens be used, or just organization owned tokens?
> If user owned tokens can be used, which tables work?

See above table, this is for a member of the org that isn't a maintainer/admin of the repo. Disclaimer being that a few of the tables that didn't work for me may work for someone with elevated permissions.

> Do any tables need permissions that only have "No access" and "Read and write" permissions?

I would have thought so, since there a a few items on the permission list that only have `no access` & `read and write` as options:
`User Based FGA Token`
- User Permissions
  - Gist
  - Profile
- Repo Permissions
  - Codespace Secrets
  - Workflow

`Org Based FGA Token`
- Org Permissions (are all set to `read-only`)
- Repo Permissions
  - Codespace Secrets
  - Workflow

The weird thing about this is that when updating my tokens to set the above to `no access` instead of `read and write` I can seemingly query the related tables ok.

Tables I checked (based on the above - we don't have tables around codespaces and it wasn't clear which tables would be affected by `Profile`)
- `github_gist`
- `github_my_gist`
- `github_actions_repository_workflow_run`
- `github_workflow`

Verified the `cache miss` from logs.
```
[INFO]  1692106196438: executeForConnection callId: 1692106196438, connectionCallId: ro_fga_user-1692106196438, connection: ro_fga_user table: github_my_gist cols: id,description,public,html_url,comments,created_at,git_pull_url,git_push_url,node_id,owner_id,owner_login,owner_type,updated_at,files,_ctx
[INFO]  1692106196438: Setting free memory interval to 100 rows
[INFO]  1692106196438: cacheEnabled, trying cache get (ro_fga_user-1692106196438)
[INFO]  1692106196438: getCachedQueryResult returned CACHE MISS - checking for pending transfers (ro_fga_user-1692106196438)
[INFO]  1692106196438: findAndSubscribeToPendingRequest returning error cache miss - this will be treated as a cache miss, so add pending item (ro_fga_user-1692106196438)
[INFO]  1692106196438: queryCacheGet returned CACHE MISS (ro_fga_user-1692106196438)
[INFO]  1692106196438: Plugin execute complete (1692106196438)
```

> Are there any tables that will throw Error: Resource not accessible by personal access token even if all read permissions are granted?

Yes, see above comments for details after testing all tables with both types of token.

> Are there any tables that return unexpected or no results?
`User Based FGA`
- `github_my_organization` returned incorrect data showing only 1 result when I was expecting 5 for my token.
- `github_my_team` seemingly only ran against the one org that was returned by the `github_my_organization` table and returned 0 results. (see log below)
- `github_organization_member` returned 0 results when 34 are returned by the classic PAT for the same org.
- `github_team` returned 0 results where 7 were expected
- `github_team_member` returned 0 results where 32 were expected

Log relating to `github_my_team` only checking one organization for the `user based fga` 
```
[INFO]  1692107016481: queryCacheGet returned CACHE MISS (ro_fga_user-1692107016481)
[DEBUG] 1692107016481: Query for table github_my_team - rate limit cost: 1 (used: 1/5000) [Nodes: 1010], resets at: 2023-08-15 14:43:37 +0000 UTC
[DEBUG] 1692107016481: github_my_team: org=theapsgroup
[INFO]  1692107016481: Plugin execute complete (1692107016481)
```

**Comment by iamjoeker** [comment]
With current versions of Steampipe and plugins, I'm still unable to query all tables with either classic or fine-grained tokens with all permissions set to read-only. Has anyone identified a work around? I see that app tokens also do not work.

**Comment by cbruno10** [comment]
Hi @iamjoeker , sorry for the late reply (just saw this) - can you please open another issue if you're still having issues? Thanks!
