### ISSUE TITLE
Join between github_repository_dependabot_alert and github_search_pull_request results in error

### ISSUE THREAD

**Issue by kikocastro** [turbot/steampipe-plugin-github#399]
**Describe the bug**
Join between github_repository_dependabot_alert and github_search_pull_request results in error.

**Steampipe version (`steampipe -v`)**
v0.21.3

**Plugin version (`steampipe plugin list`)**
v0.39

**To reproduce**
Steps to reproduce the behavior (please include relevant code and/or commands).

1. Run this query
```sql
SELECT
  alert_number
FROM
  github_repository_dependabot_alert a
JOIN
  github_search_pull_request pr
ON
  a.repository_full_name = pr.repository_full_name
WHERE
  pr.query = 'test'
  and pr.state = 'open'
```
2. And see this error:
`Error: rpc error: code = Internal desc = github: rpc error: code = Internal desc = 'List' call for table 'github_repository_dependabot_alert' is missing 1 required qual: column:'repository_full_name' operator: =
 (SQLSTATE HV000)`

**Expected behavior**
It should run, given the [documentation](https://hub.steampipe.io/plugins/turbot/github/tables/github_repository_dependabot_alert#table-usage-guide) says that the required column can be used in the `join` clause: 

> You must specify the `repository_full_name` (repository including org/user prefix) column in the where or join clause to query the table.

**Comment by ParthaI** [comment]
Hello @kikocastro, I appreciate you bringing this issue to our attention, and I apologize for the inconvenience you've experienced.

I managed to reproduce the problem using the original query. There may be an issue with Steampipe FDW while parsing the query.
However, I've made some adjustments to the query, which now appears to be functioning correctly:

```sql
with pull_req as (
  select
    repository_full_name
  from
    github_search_pull_request
  where
    query = 'is:open repo:turbot/steampipe-plugin-github'
)
select
  alert_number
from
  pull_req p
  left join github_repository_dependabot_alert d on d.repository_full_name = p.repository_full_name;
```
Could you please test this revised query and inform us if you encounter any further issues? Since I'm not entirely certain of your specific requirements for using this query, feel free to modify it as needed.

Thank you for your patience and cooperation!

**Comment by kikocastro** [comment]
it worked!
thanks 😄

**Comment by ParthaI** [comment]
@kikocastro, thank you for confirming the effectiveness of the suggested query. We're marking this issue as closed since it appears to be resolved. However, should you experience any additional problems, please don't hesitate to reopen the issue.

Thanks!
